### ISSUE TITLE
Multiple fields on the same row on the /show and /edit page

### ISSUE THREAD

**Issue by Bergrebell** [avo-hq/avo#2630] opened 2024-03-22 16:59 UTC
### Feature
Display multiple fields on the same row on the /show and /edit pages of a resource. Eg. in the screenshot below have the first-, middle- and last-name all on the same row. This could be done through giving each field a width-option of 1/3 or 2/3 or 1/2. I know it's a big one to ask but at the same time something which would benefit the whole look & feel of avo A LOT! 

### Current workarounds
Create a custom field.

### Screenshots or screen recordings
<img width="984" alt="image" src="https://github.com/avo-hq/avo/assets/6041919/60eccba9-90c8-4a02-8bfc-f413ee85350b">

### Additional context
Filament does this for example very nicely. Imho this helps a lot to make the whole UI more clean and show more information on less verical screen space. See an example [here](https://demo.filamentphp.com/shop/products/products/1/edit)

<img width="1118" alt="image" src="https://github.com/avo-hq/avo/assets/6041919/ba0a20c8-03ad-48d4-bc5e-8fe3029657d6">

**Comment by Paul-Bob** [comment] 2024-03-22 19:34
Hello @Bergrebell this is already possible with this API:

```ruby
def fields
  field :user_information, as: :heading
  row do
    field :first_name, as: :text, placeholder: "John", stacked: true, filterable: true
    field :last_name, as: :text, placeholder: "Doe", filterable: true
  end
  field :email, as: :text, name: "User Email", required: true, protocol: :mailto, filterable: true
end
```

Can't find a link to docs, maybe we missed the documentation for this one

**Comment by Bergrebell** [comment] 2024-03-24 12:29
@Paul-Bob - thanks for you prompt reply. unfortunately it breaks the layout ... 

<img width="937" alt="image" src="https://github.com/avo-hq/avo/assets/6041919/42e40f43-986e-4e85-9b36-16f0a3190b82">

<img width="938" alt="image" src="https://github.com/avo-hq/avo/assets/6041919/13ceda73-4139-4828-a1d8-3028b21b32be">

<img width="1053" alt="image" src="https://github.com/avo-hq/avo/assets/6041919/62b8a609-5408-4146-9e3b-e989cfdb5b47">

**Comment by Bergrebell** [comment] 2024-04-09 08:08
@Paul-Bob - did you have the chance to replicate the issue?

**Comment by Paul-Bob** [comment] 2024-04-09 08:27
Yes @Bergrebell the `row do` expect to be inside a `panel do` as a workaround you can try:

```ruby
def fields
  main_panel do
    field :name, as: :heading
    panel do
      row do
        field :first_name, as: :text, required: true
        field :last_name, as: :text, required: true
      end
    end
  end
end
```

**Comment by Bergrebell** [comment] 2024-04-12 08:01
@Paul-Bob - that's not really helping ... 

<img width="869" alt="image" src="https://github.com/avo-hq/avo/assets/6041919/a8b1d506-c636-4083-8fe3-30e7dc171a27">

**Comment by Paul-Bob** [comment] 2024-04-12 08:11
Maybe [stacked](https://docs.avohq.io/3.0/field-wrappers.html#stacked) would make it look better, just an workaround until we fix it

**Comment by adrianthedev** [comment] 2024-04-12 15:25
I think this is a feature, not a bug.

The idea is that you can start fast and add `field`s to the `def fields` method, and when you need to make a more advanced layout by adding `sidebar`s, `row`s and other `panel`s, you have to take over and manually add them.

So the rule is that when you need a `row` you must put it yourself in a `panel`.

**Comment by adrianthedev** [comment] 2024-04-12 15:26
Closing for now, but let's keep the conversation open.

**Closed by adrianthedev** 2024-04-12 15:26 UTC
