### ISSUE TITLE
html properties is ignored when searchable is set to true 

### ISSUE THREAD

**Issue by elassadi** [avo-hq/avo#1503] opened 2023-01-02 15:40 UTC
### Describe the bug

setting the field to searchable will cause the html properties to be ignored

```ruby 
field :article, as: :belongs_to, searchable: true,
    html: {
      edit: {
        input: {
          data: {
            action: "dummy-controller-resource#onArticleChange"
          }
        }
      }
    }
```
data attribute is not set, and the target element will not receive the change event. 

### System configuration
**Avo version**:latest

**Rails version**:latest

**Ruby version**:3.1.0

**License type**:

 - [x] Community
 - [x] Pro

**Are you using Avo monkey patches or overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [x] No

#### Impact

 - [ ] High impact
 - [ ] Medium impact
 - [ ] Low impact

#### Urgency

 - [ ] High urgency
 - [x] Medium urgency
 - [ ] low urgency

**Comment by adrianthedev** [comment] 2023-01-02 20:16
So, the attribute is getting attached. Have you also [assigned](https://docs.avohq.io/2.0/stimulus-integration.html#assign-stimulus-controllers-to-resource-views) that stimulus controller on the resource? Avo needs to know that so it can wrap the whole thing in a `data-controller` element.

Data attribute attached: 
https://share.cleanshot.com/GbZQzjw8

Stimulus action triggered:
https://share.cleanshot.com/wmj5cFWm

**Comment by elassadi** [comment] 2023-01-02 22:21
yes it's assigned and it worked fine until we add the searchable attribute

**Comment by adrianthedev** [comment] 2023-01-02 22:56
Yes. See the second link where I demo the event.

The action is being triggered in the console.
You'll see it triggered twice, and that's by design. The data attributes are added to both the text input and the hidden one. You can check what type of input it was triggered on in JS and that and make it trigger just once.

**Comment by adrianthedev** [comment] 2023-01-02 23:47
Do you think you could set up a demo repo with the issue?
You could clone https://github.com/avo-hq/avodemo and use the `course_resource_controller.js`. StimulusJS is set up and all.

**Comment by adrianthedev** [comment] 2023-01-12 12:27
Closing for now. Feel free to reopen if this persists.

**Closed by adrianthedev** 2023-01-12 12:27 UTC
