### ISSUE TITLE
Time picker not setting relative: true on create action

### ISSUE THREAD

**Issue by jmarsh24** [avo-hq/avo#3253] opened 2024-09-18 13:24 UTC
### Steps to Reproduce
https://github.com/jmarsh24/avo-time-issue
Go to this repo and create an hour. The created time will not save as the time that you save into the input.

### Expected behavior & Actual behavior
The expected behavior would be to save the time as what's input.

### System configuration
**Avo version**: 3.12.0

**Rails version**: 7.2.1

**Ruby version**: 3.2.3

**License type**:

 - [X] Community
 - [] Pro
 - [ ] Advanced

**Are you using Avo monkey patches, overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [X] No

### Screenshots or screen recordings
<img width="1507" alt="image" src="https://github.com/user-attachments/assets/ff85fb89-dae5-45fe-aa09-a14960f92b27">
<img width="1502" alt="image" src="https://github.com/user-attachments/assets/c101d3fd-9df5-4876-8fb1-236b9a609530">

The format should be Hours and Minutes without seconds because I pass `format: "HH:mm"` as an argument
<img width="1273" alt="image" src="https://github.com/user-attachments/assets/e186beba-6a89-4b2b-9802-b3606249c8ee">

#### Impact
 - [X] High impact (It makes my app un-usable.)
 - [ ] Medium impact (I'm annoyed, but I'll live.)
 - [ ] Low impact (It's really a tiny thing that I could live with.)

#### Urgency

 - [X] High urgency (I can't continue development without it.)
 - [ ] Medium urgency (I found a workaround, but I'd love to have it fixed.)
 - [ ] Low urgency (It can wait. I just wanted you to know about it.)

**Comment by Paul-Bob** [comment] 2024-10-08 13:47
Hi @jmarsh24 I found that this issue is because the active record time is handling a fixed date without any context regarding Daylight Saving Time (DST).

Rails doesn't support a time column without a date and is setting the `2000-01-01` date as default on all time values. 

When the time is input during a period when DST is active, it gets stored as UTC but with an attached date that is not on the DST period. When converted back from UTC the `2000-01-01` default date doesn't reflect the current DST status and it leads to a discrepancy of one hour. During a period when DST is not active, all behaves as expected.

I found [this issue](https://github.com/rails/rails/issues/24880) related and it helped me to understand better what is going on.

I tested this [particular answer ](https://github.com/rails/rails/issues/24880#issuecomment-1262754917)on your reproduction repository and it worked like a charm.

Check [this PR](https://github.com/jmarsh24/avo-time-issue/pull/10) that I made to your reproduction repository.

**Comment by jmarsh24** [comment] 2024-10-08 13:58
@Paul-Bob Does this mean it's something that should be changed on the application level? or on avo's end? or both? 🤔

**Comment by Paul-Bob** [comment] 2024-10-08 14:04
It would be great to have an Avo fix for this. Still researching. The only solution available right now is the suggested change on the application level

**Comment by Paul-Bob** [comment] 2024-10-08 15:16
I did test this issue on a rails console and figured out that is not an Avo problem. We would love to have a way to fix it but it would involve changing how rails handle time columns.

### Storing `current_time_in_utc` in the `start` field:
```ruby
current_time_in_utc = Time.current
# Tue, 08 Oct 2024 14:52:15.935401756 UTC +00:00

Hour.create!(start: current_time_in_utc)
# <Hour:0x0000775140067080
#  id: 23,
#  day: nil,
#  start: "2000-01-01 14:52:15.935401756 +0000",
#  end: nil,
#  created_at: "2024-10-08 14:52:30.477331000 +0000",
#  updated_at: "2024-10-08 14:52:30.477331000 +0000">
```
- `current_time_in_utc` is the current UTC time: `Tue, 08 Oct 2024 14:52:15 UTC`.
- When this time is saved in the `start` field, it’s stored as `2000-01-01 14:52:15 UTC`. 

#### Why does it store `2000-01-01`?
- The `time` column in Rails doesn’t store a date, so it defaults to `2000-01-01` as the placeholder date. Rails strips out the date from the time and assigns this default date when storing the time.

### Checking the stored time in the Bucharest timezone:
```ruby
current_time_in_utc.in_time_zone('Europe/Bucharest')
# Tue, 08 Oct 2024 17:52:15.935401756 EEST +03:00
```
- Converting `current_time_in_utc` to the `Europe/Bucharest` timezone gives: `Tue, 08 Oct 2024 17:52:15 EEST +03:00`.
- This shows the correct conversion because DST is **active** in October 2024.

### Retrieving the stored time and converting to the Bucharest timezone:
```ruby
Hour.last.start.in_time_zone('Europe/Bucharest')
# Sat, 01 Jan 2000 16:52:15.935401000 EET +02:00
```
- When retrieving the stored time and converting it to `Europe/Bucharest`, we get:

```
Sat, 01 Jan 2000 16:52:15 EET +02:00
```

The time shows **16:52:15**, but the timezone is **EET (UTC+2)** because DST is **not active** on `2000-01-01`.

### The Problem:
- The issue is that the `time` column stores the time with a fixed default date (`2000-01-01`), which doesn’t reflect the current DST status. 
- Since DST is active right now in October 2024, but the stored date (`2000-01-01`) is outside the DST period, the time gets converted incorrectly.

### Conclusion:
This is not an issue with Avo but rather with how Rails handles `time` columns. The default date (`2000-01-01`) doesn’t carry the proper context for DST, leading to a one-hour difference in times when DST is active.

I'm closing this one since is not provoked by Avo.

Whole rails console test:
```bash
╭─bob@machine ~/Projects/avo_reproduction_repos/avo-time-issue ‹main●› 
╰─$ rails c
Loading development environment (Rails 7.2.1)
avo-time-issue(dev)> current_time_in_utc = Time.current
=> Tue, 08 Oct 2024 14:52:15.935401756 UTC +00:00
avo-time-issue(dev)> Hour.create!(start: current_time_in_utc)
  TRANSACTION (0.1ms)  begin transaction
  Hour Create (0.7ms)  INSERT INTO "hours" ("day", "start", "end", "created_at", "updated_at") VALUES (?, ?, ?, ?, ?) RETURNING "id"  [["day", nil], ["start", "2000-01-01 16:52:15.935401"], ["end", nil], ["created_at", "2024-10-08 17:52:30.477331"], ["updated_at", "2024-10-08 17:52:30.477331"]]
  TRANSACTION (5.4ms)  commit transaction
=> 
#<Hour:0x0000775140067080
 id: 23,
 day: nil,
 start: "2000-01-01 14:52:15.935401756 +0000",
 end: nil,
 created_at: "2024-10-08 14:52:30.477331000 +0000",
 updated_at: "2024-10-08 14:52:30.477331000 +0000">
avo-time-issue(dev)> current_time_in_utc.in_time_zone('Europe/Bucharest')
=> Tue, 08 Oct 2024 17:52:15.935401756 EEST +03:00
avo-time-issue(dev)> Hour.last.start.in_time_zone('Europe/Bucharest')
  Hour Load (0.2ms)  SELECT "hours".* FROM "hours" ORDER BY "hours"."id" DESC LIMIT ?  [["LIMIT", 1]]
=> Sat, 01 Jan 2000 16:52:15.935401000 EET +02:00
avo-time-issue(dev)> 
```

**Closed by Paul-Bob** 2024-10-08 15:16 UTC
