### ISSUE TITLE
has_many field named `actions` causes exception

### ISSUE THREAD

**Issue by aburgel** [avo-hq/avo#3525] opened 2024-12-13 03:26 UTC
### Describe the bug

If you have a `has_many` field with the name `actions`, loading the show page for that resource will result in an exception.

### Reproduction repository for the bug

It's fairly easy to reproduce by just setting up a has_many field with the name actions.

You'll see a request in your logs to this endpoint:

`Started GET "/avo/resources/<resource name>/<id>/actions?view=show&turbo_frame=has_many_field_show_actions" for 127.0.0.1 at 2024-12-12 22:10:37 -0500`

which results in an exception (only pasting the relevant lines):

```
2024-12-12 22:10:37.299877 F [37551:puma srv tp 005 deprecators.rb:86] Rails -- Exception: NoMethodError: undefined method `new' for nil
/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/avo-3.15.3/app/controllers/avo/actions_controller.rb:79:in `set_action'
/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/activesupport-7.2.2.1/lib/active_support/callbacks.rb:362:in `block in make_lambda'
/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/activesupport-7.2.2.1/lib/active_support/callbacks.rb:179:in `block in call'
/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/actionpack-7.2.2.1/lib/abstract_controller/callbacks.rb:34:in `block (2 levels) in <module:Callbacks>'
/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/activesupport-7.2.2.1/lib/active_support/callbacks.rb:180:in `call'
/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/activesupport-7.2.2.1/lib/active_support/callbacks.rb:559:in `block in invoke_before'
/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/activesupport-7.2.2.1/lib/active_support/callbacks.rb:559:in `each'
/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/activesupport-7.2.2.1/lib/active_support/callbacks.rb:559:in `invoke_before'
/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/activesupport-7.2.2.1/lib/active_support/callbacks.rb:119:in `block in run_callbacks'
/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/i18n-1.14.6/lib/i18n.rb:353:in `with_locale'
```

### Expected behavior & Actual behavior

Not crash 😄 

### System configuration
**Avo version**: 3.15.3

**Rails version**: 7.2.2.1

**Ruby version**: 3.3.6

**License type**:

 - [X] Community
 - [X] Pro
 - [ ] Advanced

**Are you using Avo monkey patches, overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [X] No

### Additional context

I think the issue is that the routes for the avo/associations controller can be ambiguous and overlap with other controllers if the `related_name` param matches some other route. In this case it's the word `actions` but there may be others and it's certainly possible for new routes to be introduced that will conflict with other existing association names.

I would suggest changing the avo/associations controller routes to qualify the `:related_name` param. Something like `/:resource_name/:id/associations/:related_name/`. 

#### Impact

 - [ ] High impact (It makes my app un-usable.)
 - [X] Medium impact (I'm annoyed, but I'll live.)
 - [ ] Low impact (It's really a tiny thing that I could live with.)

#### Urgency

 - [ ] High urgency (I can't continue development without it.)
 - [X] Medium urgency (I found a workaround, but I'd love to have it fixed.)
 - [ ] Low urgency (It can wait. I just wanted you to know about it.)

**Comment by Paul-Bob** [comment] 2024-12-13 08:32
A workaround just came to mind:

Generate a resource with a different name and set the model class to `Action` by running the command:

`rails g avo:resource TheAction --model-class Action`

Then, use it as follows:

`field :actions, as: :has_many, use_resource: Avo::Resources::TheAction`

**Comment by aburgel** [comment] 2024-12-14 00:30
Thanks @Paul-Bob I tried your workaround and unfortunately, it doesn't work. It looks like it's the field name that ends up in the path, not the resource class name.

Seems like the best option here is to refactor the internal routes.

If these routes are meant to be for internal use, is there a reason not to refactor them? I'm sure you could do it in a backwards compatible way. Introduce the new route, deprecate the old one, and then after a release or two, remove the old one? With rails path helpers, I would hope that you don't even need to change much code beyond the controllers and routes file.

**Comment by adrianthedev** [comment] 2024-12-14 07:34
Hey @aburgel.

Let's set up a reproduction repository so we are all on the same page.
We can start work on the refactor (on our end or on the parent app) in that reproduction repository.
That will help use understand the scenario much better.
We definitely want to help you get out of this situation.
I'll have a look as well once we get that reproduction repo.

Thank you,
Adrian

**Comment by aburgel** [comment] 2024-12-15 01:27
@adrianthedev @Paul-Bob here you go: https://github.com/aburgel/avo_actions_repo

Run `rails db:seed` to get some records in the db, and then start the app, go to `/avo` and open the first Thing resource.

**Comment by aburgel** [comment] 2024-12-15 02:31
I attempted a fix (https://github.com/avo-hq/avo/pull/3529). I left it as a draft because I have no idea if a PR like that is acceptable to you. It does fix the issue, and I think it's an overall improvement because it will reduce naming collisions in the future if there are ever field names that conflict with other routes.

I'm not sure about backwards compatibility concerns. I think these are all internal routes controls, not publicly visible, so perhaps it's ok to just change them.

**Comment by Paul-Bob** [comment] 2024-12-16 01:25
@aburgel I forgot to include the `for_attribute` on my workaround suggestion. I tested it now and it works as expected, but found out that having a model `Action` has more implication at rails level (https://discuss.rubyonrails.org/t/reserved-model-names/74559/15)

I made [this PR](https://github.com/aburgel/avo_actions_repo/pull/2) that fixes your issue.

Thanks for being proactive and opening the #3529 PR I'll have a look

**Comment by aburgel** [comment] 2024-12-17 18:33
@Paul-Bob `for_attribute` fixed it, thank you! i'd still like to nudge you on #3529 since that would remove the need for a workaround 😄 

should we close this issue now that there is a workaround?

**Comment by Paul-Bob** [comment] 2024-12-18 09:29
> for_attribute fixed it, thank you! 

Awesome!

> i'd still like to nudge you on https://github.com/avo-hq/avo/pull/3529 since that would remove the need for a workaround 😄

I'm not really convinced right now about that PR. I appreciate your effort on it, and we may revisit it in the future. However, since `for_attribute` does the trick, I'd hold off on making that refactor for now.

> should we close this issue now that there is a workaround?

Closing the issue as completed but feel free to reopen or continue the conversation.

**Closed by Paul-Bob** 2024-12-18 09:30 UTC
