### ISSUE TITLE
Image stretched beyond its width

### ISSUE THREAD

**Issue by giovannetti-eric** [avo-hq/avo#2473] opened 2024-02-12 19:30 UTC
Avo version: v3.3.6

### Description:

Using images in Avo ([grid_item_component.html.erb](https://github.com/avo-hq/avo/blob/4c8efafca0a0325e2f9dc78fc5445425d4078590/app/components/avo/fields/common/files/view_type/grid_item_component.html.erb#L3) file), we're experiencing an issue where images are being stretched beyond their natural width, leading to pixelation. This problem appears to be related to the Tailwind CSS classes applied to the image's parent tag `<div class="flex flex-col h-full">`.

### Steps to Reproduce:

Navigate to the grid view where the grid_item_component.html.erb is used.
Observe the displayed images being stretched beyond their original widths.

### Current Behavior:

Images within the grid item component are stretched, not maintaining their aspect ratio. This is visually confirmed through the following screenshot:

![Screenshot 2024-02-12 at 2 20 30 PM](https://github.com/avo-hq/avo/assets/264842/cc9add41-110a-4aed-bbba-8a9a341dffc9)

### Attempted Solution:

Removing Tailwind CSS classes from the image's parent tag resolves the stretching issue, as shown here:

![Screenshot 2024-02-12 at 2 23 26 PM](https://github.com/avo-hq/avo/assets/264842/c4ed02b0-41ff-4110-8b68-69935f165202)

However, these classes are utilized across multiple content blocks, and their removal may impact the layout or functionality of other components.

### Expected Behavior:

Images should display at their natural aspect ratios without stretching.

**Comment by Paul-Bob** [comment] 2024-02-13 13:54
Hello @giovannetti-eric since which version are you experiencing this? I notice that there was a recent change on that component (https://github.com/avo-hq/avo/pull/2431) and that change was released with version `3.3.4`. I wonder if you was already experiencing this on `3.3.3`

**Comment by adrianthedev** [comment] 2024-02-13 19:21
Hey @giovannetti-eric. Coul dyou please share a full-screen screenshot to see exactly what's happening?
I can't reproduce it on my end from the provided information.

![localhost_3030_admin_resources_posts_okay-i-won-t-b8782700_edit](https://github.com/avo-hq/avo/assets/1334409/5b635137-3f11-435d-a5c9-3904262069c4)

**Comment by giovannetti-eric** [comment] 2024-02-14 15:29
> Hello @giovannetti-eric since which version are you experiencing this? I notice that there was a recent change on that component (#2431) and that change was released with version `3.3.4`. I wonder if you was already experiencing this on `3.3.3`

HI, I don't know, we just migrated from version 2 and I noticed that.

**Comment by giovannetti-eric** [comment] 2024-02-14 15:33
> Hey @giovannetti-eric. Coul dyou please share a full-screen screenshot to see exactly what's happening? I can't reproduce it on my end from the provided information.
> 
> ![localhost_3030_admin_resources_posts_okay-i-won-t-b8782700_edit](https://private-user-images.githubusercontent.com/1334409/304524598-5b635137-3f11-435d-a5c9-3904262069c4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc5MjUwNzAsIm5iZiI6MTcwNzkyNDc3MCwicGF0aCI6Ii8xMzM0NDA5LzMwNDUyNDU5OC01YjYzNTEzNy0zZjExLTQzNWQtYTVjOS0zOTA0MjYyMDY5YzQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIxNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMTRUMTUzMjUwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTM0NTY5ZDI5MGIwYmNjNWQ5NzEwN2U3NDY5MjJmNzNlNGE3NGQ4NzZhZjBkNjI3MDUzZjJhM2UzOWQyNDEyZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.xu6eiCrQsav8aU3Gptd-T1qPTYeHK7S2MlDXpMvIjJ4)

Sure, what I get:

![Screenshot 2024-02-14 at 10 32 05 AM](https://github.com/avo-hq/avo/assets/264842/a9252419-ec80-4343-96c5-9d6b6badc55b)

What I expect:

![Screenshot 2024-02-14 at 10 32 22 AM](https://github.com/avo-hq/avo/assets/264842/573f8478-b0ba-405f-bd88-939127f7036a)

**Comment by adrianthedev** [comment] 2024-02-14 16:07
I see you're using `stacked: true` option on all fields. Is that correct?

**Comment by giovannetti-eric** [comment] 2024-02-16 14:41
@adrianthedev Honestly I don't know, I'm currently only using this interface, I'm not the one that configured it, @olivierbuffon is the one that can answer this question.

**Comment by olivierbuffon** [comment] 2024-02-16 15:19
@adrianthedev yep we're using the `config.field_wrapper_layout = :stacked` in our AVO main configs

**Comment by adrianthedev** [comment] 2024-02-21 07:02
Then you might need to eject the `Avo::FieldWrapperComponent` component and apply some CSS tweaks yourself. 
`bin/rails generate avo:eject --component Avo::FieldWrapperComponent`
Careful, this will affect all the fields on show and edit.

The `stacked` mode is primarily intended for full-width usage.

**Comment by adrianthedev** [comment] 2024-02-21 07:02
Will close for now, but please reach out if you still need assistance.

**Comment by Paul-Bob** [comment] 2024-02-21 10:09
This issue was inserted in [this PR](https://github.com/avo-hq/avo/pull/2431). The issue seems to be present only when using `stacked` fields.

The mentioned PR is getting back-ported to avo2 since it fixes the image name being correctly displayed. Please back-port the fix for this issue to avo2.

**Closed** 2024-02-22 16:43 UTC
