### ISSUE TITLE
Syntax Errors with avo.js in Production Build

### ISSUE THREAD

**Issue by JensRavens** [avo-hq/avo#911] opened 2022-05-19 16:06 UTC
### Describe the bug
I have an issue with assets in a deployed app using Avo where the `avo.js` contains a syntax error on production builds.

### Steps to Reproduce
- create an app with the given versions (using js-bundling and scss handled via sprockets)
- add avo according to the documentation, no modifications
- deploy to Heroku

### Expected behavior
- avo's JS should work out of the box

### Actual behavior
- JS parsing fails in production in current versions of Chrome, Safari, and Firefox.
- Error (`Uncaught SyntaxError: Invalid or unexpected token (at avo.js:1:6385)`, deployed script is here: https://eaze.nerdgeschoss.de/avo-assets/avo.js)
- because of missing JS, most of Avo doesn't work (easiest thing to spot: the global search field doesn't show).

### System configuration
**Avo version**: 2.7.0

**Rails version**: 7.0.3

**Ruby version**: 3.0.3

**License type** (Community or Pro): Pro

#### Impact

 - [x] High impact
 - [ ] Medium impact
 - [ ] Low impact

#### Urgency

 - [ ] High urgency
 - [x] Medium urgency
 - [ ] low urgency

**Comment by JensRavens** [comment] 2022-05-19 16:09
If I see correctly, `avo.js` seems to be the same in dev and prod builds, but I only get this error in prod builds 🤔

**Comment by adrianthedev** [comment] 2022-05-19 19:07
Hey @JensRavens could this be something specific to your setup? [Avodemo](https://avodemo.herokuapp.com/avo/dashboards/dashy) looks ok with 2.7.0. Happy to troubleshoot it with you.

You are correct. The bundles should be the same in all enviroments.

**Comment by adrianthedev** [comment] 2022-05-19 19:20
Do you have any other js file added to Avo?

**Comment by JensRavens** [comment] 2022-05-20 05:45
Nope, the setup is as simple as possible and especially the aaset pipeline is a standard sprocket setup. What surprises me is that in prod the file is called `/avo-assets/avo.js` - shouldn't it be appended with a digest to enable caching?

**Comment by JensRavens** [comment] 2022-05-20 07:09
I finally found the culprit. I'm using Cloudflare in production which automatically minifies js, css and html - and that broke the js file in a recent update of Avo. The moment I disabled the option, the admin tool is working again.

As far as the issue goes, feel free to close this. My remaining question though is: Why isn't the avo.js file minified and digested in the first? I'm not quite sure how assets are handled in avo and why they don't show up in the file system after `rails assets:precompile`.

**Comment by adrianthedev** [comment] 2022-05-20 07:24
Ok. I'm glad we found where the issue was. That's the most daunting thing :)

Regarding modification, I think I just didn't enable it when we switched to `esbuild`. I might try it with the next release.
I'm curious though, if Cloudflare tries to minify that. If it's going to break it again. 
**If I post a prerelease would you be able to test it?**

Regarding not compiling Avo's assets on `rails assets:precompile`, **that's a feature, not a bug**. We compile the assets ahead of time and deploy the gem with them compiled. This way, the host apps don't have to manage Avo's asset pipeline (maybe you don't have node in your build process, or it's a different version, etc.).
We just believe it's simpler this way and it's less complex for the developer's deployment process.

**Comment by adrianthedev** [comment] 2022-05-25 11:35
It seems that the js [does get](https://github.com/avo-hq/avo/blob/main/package.json#L14) minified when packed (so for you it's the same asset file for development and production).

Not sure what Cloudflare does to it. Maybe it minifies it even further and somehow brakes it?

**Comment by adrianthedev** [comment] 2022-05-25 11:36
Closing for now, but let me know if there's something I can do on my end to troubleshoot/fix this.

**Closed by adrianthedev** 2022-05-25 11:36 UTC
