### ISSUE TITLE
Set value for text (number) field

### ISSUE THREAD

**Issue by Sweex99** [avo-hq/avo#1462] opened 2022-11-29 09:25 UTC
### System configuration
**Avo version**: 2.20.0

**Rails version**: 7.0.4

**Ruby version**: 3.1.2

**License type**

 - [ ] Community
 - [x] Pro

**Are you using Avo monkey patches or overriding views or view components?**

 - [x] Yes. If so, please post code samples.
 - [ ] No

### Screenshots or screen recordings

Hi! Trying generate number field by edit component
<img width="579" alt="Screenshot 2022-11-29 at 11 17 07" src="https://user-images.githubusercontent.com/27281496/204488848-cf732233-7bba-41ad-a2f2-e1c79aa0490b.png">

created number field object with value
<img width="506" alt="Screenshot 2022-11-29 at 11 18 43" src="https://user-images.githubusercontent.com/27281496/204489179-a2ca8883-aee1-4b6a-bfd4-d6dd30f9fde0.png">

but field is empty (but should be - 321)

<img width="1002" alt="Screenshot 2022-11-29 at 11 19 30" src="https://user-images.githubusercontent.com/27281496/204489258-79c514a2-a46c-41e3-9602-3fe75428b0a1.png">

investigated this issue in source code, and found peace of code like
<img width="594" alt="Screenshot 2022-11-29 at 11 22 34" src="https://user-images.githubusercontent.com/27281496/204490026-1a1ac031-7b85-4e01-bafe-5db0f31f3462.png">

Could you pls help me out, how can i set value for field?

**Comment by adrianthedev** [comment] 2022-11-29 09:56
Are you sure you are on version 2.20?
This file looks like there isn't that commented piece of code.
https://github.com/avo-hq/avo/blob/36136880297c96ca51c8271db91e2df3abae33f4/app/components/avo/fields/number_field/edit_component.html.erb

**Comment by adrianthedev** [comment] 2022-11-29 09:58
Also, [the docs](https://docs.avohq.io/2.0/native-field-components.html) specify that the usage of native fields is different than you're code samples.

You can use it like this:

```erb
<%= avo_edit_field :name, as: :number, form: form %>
```

**Comment by Sweex99** [comment] 2022-11-29 10:04
went something wrong
<img width="597" alt="Screenshot 2022-11-29 at 12 03 34" src="https://user-images.githubusercontent.com/27281496/204499592-5b69cf79-a3ab-4a05-bfa4-cbc971f9e022.png">
view
<img width="670" alt="Screenshot 2022-11-29 at 12 04 10" src="https://user-images.githubusercontent.com/27281496/204499665-b9786441-4b22-467e-9e6d-80a68a53b2a6.png">

**Comment by adrianthedev** [comment] 2022-11-29 10:06
ok. please create a reproduction repository where I can see and test the issue.

You can create one of your own or clone this one https://github.com/avo-hq/avo-reproduction.

**Comment by Sweex99** [comment] 2022-11-29 10:06
> Are you sure you are on version 2.20? This file looks like there isn't that commented piece of code. https://github.com/avo-hq/avo/blob/36136880297c96ca51c8271db91e2df3abae33f4/app/components/avo/fields/number_field/edit_component.html.erb
screenshot related to text field, but issue the for both (text, number)
<img width="941" alt="Screenshot 2022-11-29 at 12 05 11" src="https://user-images.githubusercontent.com/27281496/204499943-8799477d-a4c8-4788-93a1-b2ac163c096a.png">

**Comment by adrianthedev** [comment] 2022-11-29 10:25
That doesn't mean you're using avo 2.20 on that app, but that it's present on the system.

This will list your current avo package.
`bundle list | grep 'avo'`

But, please create a reproduction repo so I can test it.

**Comment by adrianthedev** [comment] 2022-12-03 20:04
CLosing for now. Feel free to reopen if you create a reproduction repo.

**Closed by adrianthedev** 2022-12-03 20:04 UTC
