### ISSUE TITLE
When `config.root_path` doesn't equal root mount point in routes.rb, "Custom Tool" warning is thrown

### ISSUE THREAD

**Issue by johlym** [avo-hq/avo#1183] opened 2022-08-30 05:58 UTC
### Context
I just got Avo set up with a small app of mine, and during the configuration process, I tweaked a few things here and there to see how I liked them. At some point, I had:

```rb
# routes.rb

...
  authenticate :admin do
    mount Avo::Engine => '/'
  end
...
```

and 

```rb
# avo.rb

...
  config.root_path = '/admin'
...
```

Naturally, Avo operated out of `/` as defined in the `routes.rb` file. 

This appears to be related to #1030 and the code referenced from that issue but wanted to bring this up because once I realized what was causing this, I would have expected Avo to warn or error out because of the discrepancy. 

The latter configuration wasn't taking precedence, and Avo was indeed operating at the root, but elsewhere thought it was not and disabled itself. Matching these two values up solved this.

 
### System configuration
**Avo version**: 2.13.1

**Rails version**: 7.0.3.1

**Ruby version**: 3.1.2

**License type** (Community or Pro): Community

**Comment by adrianthedev** [comment] 2022-09-15 11:19
Hey @johlym. Apologies for the late reply.

I assume the issue is fixed now, right? You set the correct paths and all is well.

Yes, I agree we could make Avo smarter in that area. We assumed you'll set the correct paths in the setup process.
We want to put our time to good use and we're focusing on features and issues that are more painful for developers

**Comment by adrianthedev** [comment] 2022-09-15 11:19
Closing for now. Feel free to reopen if you think it's necesarry.

**Closed by adrianthedev** 2022-09-15 11:19 UTC

**Comment by johlym** [comment] 2022-09-15 16:22
Yes, everything's okay with the correct paths set. Thanks for looking at this, @adrianthedev!

**Comment by adrianthedev** [comment] 2022-09-15 16:23
Anytime! Again, apologies for the delay. It slipped through the cracks.
