### ISSUE TITLE
Bug: Resource and Global Search broken

### ISSUE THREAD

**Issue by andresyebra** [avo-hq/avo#1940] opened 2023-09-05 19:03 UTC
### Resource and Global Search broken
Global search and resource search  not working when the model `has_many_attached :media` configuration for ActiveStorage. 

When the model `has_one_attached :media ` **works** perfectly. 

The search in general is prepared to display an image from model, but not many images when association is has_many.

**Error**: 
`NoMethodError (undefined method `to_model' for #<ActiveStorage::Attached::Many:0x000000010bb37b38 @name="media", @record=#<Merchandise id: 5, name: "For Sport", slug: "for-sport", merch_type: "shirt", description: "descriptionn", conditions: [{"icon"=>"question", "label"=>"label"}], title: "title for sport", sub_title: "sub title", fulfillment: "dropshipping", artist_id: 1, release_id: 12, created_at: "2023-08-24 19:40:31.963378000 +0000", updated_at: "2023-08-28 14:50:37.950945000 +0000">>):`

**Model**: 
```
class Merchandise < ApplicationRecord
  include Ransackable
  extend FriendlyId
  friendly_id :name, use: :slugged

  has_many_attached :media
end
```

**Resource:** 
```
class MerchandiseResource < Avo::BaseResource
  self.title = :slug
  self.includes = []
  self.search_query = -> { scope.ransack(name_cont: params[:q], m: "or").result(distinct: false) }
  self.find_record_method = ->(model_class:, id:, params:) { model_class.friendly.find id }

  field :id, as: :id, link_to_resource: true
  field :name, as: :text, link_to_resource: true
  field :slug, as: :text, link_to_resource: true, only_on: %i[index show]

  field :media, as: :files, is_image: true, as_avatar: :rounded, full_width: true,
                accept: "image/.jpg, .jpeg, .png, .gif"
end
```

### System configuration
**Avo version**: 2.39.0

**Rails version**: 7.0.4

**Ruby version**: 3.2.0

**License type**

 - [x] Community
 - [x] Pro

**Are you using Avo monkey patches, overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [x] No

### Screenshots or screen recordings
![Screenshot 2023-09-05 at 11 58 55 a m](https://github.com/avo-hq/avo/assets/10139341/7abaa452-5cd1-49aa-a3a7-f5bf5fabf32d)

![Screenshot 2023-09-05 at 11 58 41 a m](https://github.com/avo-hq/avo/assets/10139341/8dffe6da-88ec-49c7-bb80-ade72e381e44)

**Comment by Paul-Bob** [comment] 2023-09-06 03:57
Hello @andresyebra thanks for the detailed report, I was able to reproduce it.

The issue is caused by using the `as_avatar` option on a `files` field. The `as_avatar` option should be used on just **one** file.

You can fix this issue by removing the `as_avatar` option or to use something like this for avatar on `files` field:

```ruby
field :media, as: :files, is_image: true, as_avatar: :rounded do |model|
  model.media.first # implement your own logic to fetch the desired avatar
end
```

I'll close the issue as solved but fell free to comment on it or even to reopen it if you find any obstacles while fixing this.

**Closed by Paul-Bob** 2023-09-06 03:57 UTC
