### ISSUE TITLE
Downloaded files always have the filename "true"

### ISSUE THREAD

**Issue by iainbeeston** [avo-hq/avo#1174] opened 2022-08-26 13:49 UTC
### Describe the bug

If you upload a file in a file field, you can see the original filename in avo. When you download the file again, the downloaded file always has the name "true" (but still has the original filename extension).

### Steps to Reproduce
1. Find a project in the demo app https://avodemo.herokuapp.com/avo/resources/projects
2. Edit it and upload a file
3. Save
4. Check that the page shows the original name of the file
5. Download the file again

### Expected behavior & Actual behavior
I'd expect the downloaded file to have the original filename, instead it will be called "true"

### System configuration
**Avo version**: 2.13.1

**Rails version**: 7.0.3.1

**Ruby version**: 3.1.2

**License type**:

 - [ ] Community
 - [x] Pro

#### Impact

 - [ ] High impact
 - [x] Medium impact
 - [ ] Low impact

#### Urgency

 - [ ] High urgency
 - [x] Medium urgency
 - [ ] low urgency

**Comment by adrianthedev** [comment] 2022-08-26 13:57
I see it. It will be fixed in the next release.

Thanks!

**Comment by adrianthedev** [comment] 2022-08-26 14:25
@iainbeeston can you try out https://rubygems.org/gems/avo/versions/2.13.6.pre.1 and see if the issue persists?

**Comment by iainbeeston** [comment] 2022-08-26 14:50
@adrianthedev 2.13.pre.1 crashes my resource show page entirely! (I'm not sure what the issue is exactly, the page renders correctly on 2.13.1)

![Screenshot 2022-08-26 at 15 48 33](https://user-images.githubusercontent.com/111963/186931760-f802a7b9-c86a-4309-a56a-87f1a1745be3.jpg)


![Screenshot 2022-08-26 at 15 49 30](https://user-images.githubusercontent.com/111963/186931955-e50ce8b4-dd70-4713-9a36-92258bcd63a2.jpg)

**Comment by iainbeeston** [comment] 2022-08-26 14:59
Interestingly, the bug only seems to happen in production on a server. When I try this locally in development it uses the original filename.

**Comment by adrianthedev** [comment] 2022-08-26 15:06
It could be the difference in acitve storage providers. Can you confirm you're using local in development and a cloud one on prod?

Also, what version if active storage are you using?

**Comment by adrianthedev** [comment] 2022-08-26 15:06
Probably the latest? I see you're on Rails 7.

**Comment by adrianthedev** [comment] 2022-08-26 15:09
Actually I see it in the stacktrace. I'll play around with it and see how this can be fixed

**Comment by iainbeeston** [comment] 2022-08-26 15:13
Yes I'm using the local storage service in development and aws on the server. As I mentioned above, the demo app seems to have the same issue (I'm not sure what services that is using?)

**Comment by adrianthedev** [comment] 2022-08-26 17:54
Hey @iainbeeston. I can't seem to replicate this issue. I tried in development (my machine) with `local` and `amazon` adapters.

Can you check the logs for the production app and confirm that it's failing with the same exception?

I also published `pre.2` with a minor tweak and [outputting the file object](https://github.com/avo-hq/avo/pull/1175/files#diff-a5922d5149f74c779014ad05a141a41d8774ddc125579b8137d95c8a1de0a890R24) to see what you get there.

Please try it out and let me know the results.

**Comment by iainbeeston** [comment] 2022-08-26 19:51
Can you reproduce it on the demo app using the instructions above? I get the exact same issue both on my own site and on the avo demo site.

**Comment by iainbeeston** [comment] 2022-08-26 20:12
Or do you mean you can reproduce the issue with downloads all being called “true” but you can’t reproduce the error I’m seeing?

**Comment by adrianthedev** [comment] 2022-08-26 20:14
Sorry about not being clear. I managed to reproduce the 'true' filename bug. 
I tried to fix it and released pre.1
You reported the full page crash with screenshots, and that's what I can't reproduce.

**Comment by iainbeeston** [comment] 2022-08-29 16:22
I've tried pre.2 to see if that helps, but unfortunately I get this error whenever I load the resource show page, both for the local storage service and with the aws storage service (I can't even see the download link to try it out):

```
ActionView::Template::Error: undefined method `service_url' for #<ActiveStorage::Attachment id: "92abeec3-58b5-459a-88fa-5c0aff8f3568", name: "images", record_type: "Hotel", record_id: "30b2c819-32b3-4678-99c1-971d861ec6f0", blob_id: "d3af9c1c-f88d-4731-b048-1d366f113f32", created_at: "2022-08-29 15:41:14.093978000 +0000">
```

![Screenshot 2022-08-29 at 15 17 32](https://user-images.githubusercontent.com/111963/187247818-02b1f6d2-6331-4322-b9dc-7fc5349a931a.jpg)

**Closed** 2022-08-30 19:17 UTC
Labels: bug
