### ISSUE TITLE
Apply the OR logic also for custom dynamic filters

### ISSUE THREAD

**Issue by pjmuller** [avo-hq/avo#3136] opened 2024-08-14 08:35 UTC
### Feature
in Avo 3.11 you introduced https://github.com/avo-hq/avo-dynamic_filters/pull/52 however this doesn't seem to work yet for CUSTOM dynamic filters.

```ruby
class Avo::Resources::Person < Avo::BaseResource
   def filters
     dynamic_filter :firstname, as: :text
   end
end
```

If I know do this twice (see screenshot)
![Screenshot 2024-08-14 at 10 24 07](https://github.com/user-attachments/assets/df4fc8fc-7bda-4994-9d14-bb79af8e0be5)

I see this query in the rails logs

```sql
SELECT "people".*
FROM   "people"
WHERE 
    ("people"."firstname" ILIKE '%foo%' OR  "people"."firstname" ILIKE '%bla%') -- this seems to come from ?standard? dynamic filters
    AND    ("people"."firstname" ilike $1) -- this is coming from my custom dynamic filter
   AND    ("people"."firstname" ilike $2)
```

where $1 = foo and $2 = bla

So 2 issues
1. he seems to inject both the "standard" dynamic filters as well as "custom" dynamic filters, see https://www.loom.com/share/ef7a4e082ec146148221aed1db23be34 for a clearer example
2. within the custom dynamic filters he is not grouping them

### Current workarounds
Ask people never to create the same filter twice

**Comment by Paul-Bob** [comment] 2024-08-14 18:49
I think I identified the issue but could you please share the dynamic filter definition?

Was it just `dynamic_filter :firstname, as: :text`?

**Comment by Paul-Bob** [comment] 2024-08-14 19:00
What you mention on the loom from second `20` to second `34` about the injected custom logic from our side that you think shouldn't be injected was a design choice discussed [here](https://github.com/avo-hq/avo-dynamic_filters/pull/26#discussion_r1469346200).

Essentially, we always apply our filtering system first. If you provide a `query`, it will be applied to the results produced by that system.

It sounds like in your case, you want to replace our filtering logic with the logic from your `query` block. Is that correct?

**Comment by pjmuller** [comment] 2024-08-16 07:06
@Paul-Bob 
- the dynamic_field is defined as `ynamic_filter :firstname, as: :text` + the `conditions` and `query` code you see in my loom at :42
- feels strange (for my usecase) that something else is still applied first, when I'm OVERWRITING the query (like you would overwrite any other ruby method, class, ... for that matter) you expect to have a full overwrite and control.
    -  Is there a way I can bypass the standard dynamic_filter being injected? I would guess by using non standard `condition` names -> but then why was the `contains2` condition failing in my loom around 02:00

**Comment by Paul-Bob** [comment] 2024-08-16 07:45
> - the dynamic_field is defined as `ynamic_filter :firstname, as: :text` + the `conditions` and `query` code you see in my loom at :42

When grouping, we were using the filter `id` to make the query, and the `id` on a custom dynamic filter doesn't always refer to a DB column. I already made a PR to use the `query_attributes` instead of the filter `id`.

> - feels strange (for my usecase) that something else is still applied first, when I'm OVERWRITING the query (like you would overwrite any other ruby method, class, ... for that matter) you expect to have a full overwrite and control.

Makes sense

> -  Is there a way I can bypass the standard dynamic_filter being injected? I would guess by using non standard `condition` names -> but then why was the `contains2` condition failing in my loom around 02:00

There is not without a monkey patch yet, let's continue this discussion here https://github.com/avo-hq/avo/issues/3143

**Comment by Paul-Bob** [comment] 2024-08-16 13:25
@pjmuller the issue with the `firstname` is provoked by your custom `query`.

We're applying the grouping that's why you can see that `OR` _from ?standard? dynamic filters_ but then your custom query is applying the `AND` on top of that.

`query` is called once for "hahaha" and then called again for "foobar"

I don't totally understand why are you overriding the `query` since it seems to apply the same logic as the dynamic filter would apply for you.

#

For the number filter, where the grouping is never applied from our side, I guess the issue is that the filter ID (the one passed through params) does not match any DB column can you confirm, please?

**Comment by Paul-Bob** [comment] 2024-08-20 13:40
When reproducing this issue, I noticed that `query` should be called only once, and `filter_param.value` should be an array of values when multiple filters are applied.

```ruby
dynamic_filter :name, query: -> {
  # When 1 name filter is applyed
  # filter_param.value => "Paul" 
 
  # When 2 filters are applied
  # filter_param.value -> ["Paul", "Joaquim"]
}
```

Currently, the `query` is called separately for each value, first with `"Paul"` and then with `"Joaquim"`.

**Comment by Paul-Bob** [comment] 2024-09-03 12:44
Closing this one as completed, let me know if there are any questions.

**Closed by Paul-Bob** 2024-09-03 12:44 UTC
Labels: Bug
