### ISSUE TITLE
Fields in panels don't appear on index view

### ISSUE THREAD

**Issue by iainbeeston** [avo-hq/avo#1439] opened 2022-11-18 18:01 UTC
### Describe the bug

If I put a field inside a panel, it no longer appears in the table on an index view.

### Steps to Reproduce
1. Add a field to a resource
2. Confirm it is visible on an index view
3. Edit the resource to put the field inside a panel

### Expected behavior & Actual behavior

The field will now disappear from the index view. I wouldn't expect a panel to affect whether a field appears on the index view or not. Adding `show_on: :index` doesn't seem to fix the issue.

### System configuration
**Avo version**: 2.18.1

**Rails version**: 7.0.4

**Ruby version**: 3.1.2

**License type**:

 - [ ] Community
 - [x] Pro

**Are you using Avo monkey patches or overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [x] No

#### Impact

 - [ ] High impact
 - [x] Medium impact
 - [ ] Low impact

(It just means I can't use panels for some things)

#### Urgency

 - [ ] High urgency
 - [x] Medium urgency
 - [ ] low urgency

**Comment by adrianthedev** [comment] 2022-11-19 22:39
Hey @iainbeeston. Yes. That's a feature, not a bug.
The way we thought about it was that everything in the root level (not nested in panels, tabs, or sidebar) is going to be visible on the index page. 
That's because you use panels to organize the fields on the `Show view`. You don't get to "see" the panel on the `Index` view.

**Comment by iainbeeston** [comment] 2022-11-20 08:37
Ah ok, that’s interesting. I just view tabs and panels as a visual thing, to make it easier for users to find what they need and make large forms look more attractive.

Should it be possible to override the default behaviour using “show_on: :index” though?

**Comment by adrianthedev** [comment] 2022-11-20 16:02
Hmmm. It requires a bit of work. I would merge a PR if there were one.

**Comment by adrianthedev** [comment] 2022-12-03 20:16
Closing for now. Feel free to reopen if you have new info.

**Closed by adrianthedev** 2022-12-03 20:16 UTC
