### ISSUE TITLE
Money field does not show up

### ISSUE THREAD

**Issue by jasdeepsingh** [avo-hq/avo#3228] opened 2024-09-06 20:18 UTC
### Describe the bug

Using the avo money field on a resource as follows:

```
class Avo::Resources::Product < Avo::BaseResource
  def fields
    field :id, as: :id
    field :price, as: :money, currencies: %w[EUR USD]
  end
end
```

However, the field is not showing up or rendering in UI (create/edit forms). If I change the field type to `number`, it works fine. The actual field name in DB is `price_cents`

### Steps to Reproduce
1. Create a new Rails 7.2.1 project. 
2. Add a new Avo Resource
3. Add a money field on the model/resource
4. Try to render the money field in the Avo dashboard.

### Expected behavior & Actual behavior

Expected result: Money field shows up in the create/edit form. 
Actual result: Money field does not show up in create/edit form

### System configuration
**Avo version**: 3.12.0

**Rails version**: 7.2.1

**Ruby version**: 3.3.4

**License type**:

 - [x] Community
 - [ ] Pro
 - [ ] Advanced

**Are you using Avo monkey patches, overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [x] No

### Screenshots or screen recordings

N/A

### Additional context

```
gem "avo", ">= 3.12.0"
gem "money-rails", "~> 1.12"
gem "avo-money_field"
```

#### Impact

 - [x] High impact (It makes my app un-usable.)
 - [ ] Medium impact (I'm annoyed, but I'll live.)
 - [ ] Low impact (It's really a tiny thing that I could live with.)

#### Urgency

 - [x] High urgency (I can't continue development without it.)
 - [ ] Medium urgency (I found a workaround, but I'd love to have it fixed.)
 - [ ] Low urgency (It can wait. I just wanted you to know about it.)

**Comment by Paul-Bob** [comment] 2024-09-09 07:20
Hello @jasdeepsingh it's working as expected on our demo https://main.avodemo.com/avo/resources/products/new

Please provide a minimal reproduction repository where we can reproduce it.

**Comment by butschi** [comment] 2024-09-11 08:07
I had the same. In my case it was because I had the database field configured to be nullable, meaning both the value and the currency could become null.

For me the solution was to default the value to 0 and the currency to my main currency. Then the Avo money fields would show up in the forms.

**Comment by Paul-Bob** [comment] 2024-09-11 14:12
Thanks for the reproduction repository, I was able to identify the issue. You're missing the `monetize :price_cents` on the model (https://github.com/metaware/avo-money-bug/pull/1). I'm also updating the docs with this piece of information.

I'm closing as solved, please let me know if the issue persists.

**Closed as completed** 2024-09-11 14:13 UTC
Labels: Waiting on Reproduction
