### ISSUE TITLE
Localization not working

### ISSUE THREAD

**Issue by jmarsh24** [avo-hq/avo#3445] opened 2024-11-20 16:13 UTC
### Describe the bug
When you have an application with en and de locales. The home translation on the de page should be "Startseite" but instead it remains home on both en/de

### Steps to Reproduce
I have created a reproducible repo below.
https://github.com/jmarsh24/localized_dashboard/pull/2

Visit "http://localhost:3000/de/avo/resources/posts" and notice that the home translation is not translated.
![Image](https://github.com/user-attachments/assets/00771a27-4fea-4a1c-a2de-1ad5d745f806)

### Expected behavior & Actual behavior
I would expect home to be translated to "Startseite" instead of remaining home./

### System configuration
**Avo version**:
3.14.1

**Rails version**:
8.0.0
**Ruby version**:
3.3.5

**License type**:

 - [ ] Community
 - [X] Pro
 - [ ] Advanced

**Are you using Avo monkey patches, overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [X] No

#### Impact

 - [ ] High impact (It makes my app un-usable.)
 - [X] Medium impact (I'm annoyed, but I'll live.)
 - [ ] Low impact (It's really a tiny thing that I could live with.)

#### Urgency

 - [X] High urgency (I can't continue development without it.)
 - [ ] Medium urgency (I found a workaround, but I'd love to have it fixed.)
 - [ ] Low urgency (It can wait. I just wanted you to know about it.)

**Comment by Paul-Bob** [comment] 2024-11-20 18:12
Thanks for sharing the detailed issue and repo, @jmarsh24!

The problem is that `add_initial_breadcrumbs` runs before `localize`, so the localization isn't applied yet.

**Comment by Paul-Bob** [comment] 2024-11-21 09:29
After exploring different possibilities I end up noticing that the solution with less friction to implement is to remove the custom concern and override the `set_avo_locale` around action method.

I've done a commit with this approach https://github.com/jmarsh24/localized_dashboard/pull/6/files

Closing this issue as completed, we'll include this approach on the documentation.

**Comment by jmarsh24** [comment] 2024-11-21 10:27
Thank you for the fix! You are a life saver! Sorry for being such a pain in the but about this one, but localization is a requirement on this client project.

**Comment by jmarsh24** [comment] 2024-11-21 11:37
@Paul-Bob @adrianthedev 
There is still an issue with names for dashboard cards. 

![Image](https://github.com/user-attachments/assets/a7730168-a7ad-44c4-b458-a727bb291a7b)
![Image](https://github.com/user-attachments/assets/31ef1cbf-7b7e-49a0-a462-4d487023846d)

If I change to a proc I get the following error.
![Image](https://github.com/user-attachments/assets/c9a98dc8-c9df-4cc5-9d6b-da5fd2067da4)
![Image](https://github.com/user-attachments/assets/6ced6256-ed4b-4f88-87b2-b505ffd33a76)

**Comment by Paul-Bob** [comment] 2024-11-21 11:49
@jmarsh24 thanks for opening this issues and setting the reproduction repositories so we can jump straight to the issue.

As Adrian said:

> This is definitely something that we can improve on going forward.
It's a very valid use-case.

We reviewed this and noticed a lack of clear guidance on how to achieve it. While we had documentation sections on scoping Avo under a route, adding default URL options, and using the `set_avo_locale` method, there was no connection tying these topics together.

After connecting all the topics, we arrived at [this comprehensive recipe](https://docs.avohq.io/3.0/guides/localization-scope.html), which I believe covers all the necessary steps to achieve localization within a routing scope in Avo.

---

> There is still an issue with names for dashboard cards.

Regarding the errors you're seeing, already merged a PR for dashboards to accept proc as a name but isn't released yet. It will be possible after the next release. 

Thank you.

**Closed by Paul-Bob** 2024-11-21 11:49 UTC

**Comment by jmarsh24** [comment] 2024-11-21 12:13
@Paul-Bob @adrianthedev 

We discovered one more issue that's reproducible on the repo I have created if you run on `bin/rails dev:cache`

![Image](https://github.com/user-attachments/assets/1f8db19d-c672-4434-9181-f8e55c000097)

You can see the german translation is used in the new resource create button.

**Comment by Paul-Bob** [comment] 2024-11-21 13:36
> [@Paul-Bob](https://github.com/Paul-Bob) [@adrianthedev](https://github.com/adrianthedev)
> 
> We discovered one more issue that's reproducible on the repo I have created if you run on `bin/rails dev:cache`
> 
> 
> You can see the german translation is used in the new resource create button.

Created this issue https://github.com/avo-hq/avo/issues/3449.
Let's continue the discussion there. 

Let us know if you want to give it a try.
