### ISSUE TITLE
Issue adding nested records on creating

### ISSUE THREAD

**Issue by angel-checkealos** [avo-hq/avo#1594] opened 2023-02-22 13:43 UTC
### System configuration
**Avo version**: 2.26

**Rails version**: 7.0.4

**Ruby version**: 3.1.2

**License type**

 - [ ] Community
 - [ X] Pro

**Are you using Avo monkey patches or overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [X ] No

### Screenshots or screen recordings

Check this public repository with the code and install instructions:
https://github.com/pocopuede/avo_nested

Follow in the README the steps to reproduce the error.

It appears to be related with the fields in the from added in partial view.
<img width="1197" alt="Screenshot 2023-02-22 at 14 40 53" src="https://user-images.githubusercontent.com/106058674/220636549-3bac6fae-49e5-4733-9b17-403b9b1fea3a.png">

This fresh app has been created so quickly. Sorry if are any error in coding.

Waiting for your help. Thanks in advance
Angel Gonzalez

**Comment by adrianthedev** [comment] 2023-02-22 13:53
Hey @angel-checkealos.
I think the issue is a typo in your field declaration
in `app/views/avo/partials/_qualify_question_answer.html.erb` instead of `as: :string` switch to `as: :text`

**Comment by adrianthedev** [comment] 2023-02-22 13:55
I know Rails uses `string` and `text` for migrations and you might be tempted to declare them the same, but try to think about the fields as what is going to be rendered on the screen. `as: :text` will render an `input[type="text"]`; `as: :textarea` -> `input[type="text"]` and so on.

**Comment by adrianthedev** [comment] 2023-02-22 13:55
Closing for now. Please feel free to reopen if this still persists.

**Closed by adrianthedev** 2023-02-22 13:55 UTC
