### ISSUE TITLE
Load order of <script> tags unclear (unable to integrate google maps)

### ISSUE THREAD

**Issue by Bergrebell** [avo-hq/avo#1416] opened 2022-11-08 16:20 UTC
### Context
 i want to integrate a google maps into avo via avo-tools following this guide here: https://betterprogramming.pub/integrate-google-maps-with-a-rails-app-5e5012e8cf16
 
i've created a avo:tool via `bin/rails g avo:tool map` and my `_head.html.erb` looks like this:

```
<%= javascript_importmap_tags "avo.custom" %>
<script src="https://maps.googleapis.com/maps/api/js?key=<%= Rails.application.credentials[:google_maps_js_api_key] %>&callback=initMap" data-turbolinks-eval="false"></script>
```

- then i've added the callback function initMap() to `avo.custom.js`

**Expected result:**
- the callback function initMap should be triggered as soon as the google maps script is loaded 

**Actual result:**
- a JS exception "initMap is not a function" is raised

**Assumption:**
- i assume, that the load-order is somehow messed. 

**Question:**
- What do i need to do to get this fixed? Is this even the recommended way of loading external scripts in Rails 7? I've seen Chris Oliver from GoRails do it the same, but it still feels kind of strange. Unfortunately I am still a bit lost with importmaps etc. in Rails 7. 

### System configuration
**Avo version**:
2.18 & 2.19
**Rails version**:
7.0.4
**Ruby version**:
3.1.2
**License type**

 - [ ] Community
 - [x] Pro

**Are you using Avo monkey patches or overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [n] No

### Screenshots or screen recordings
<img width="1392" alt="image" src="https://user-images.githubusercontent.com/6041919/200619054-718c384b-5e37-43eb-aa4a-d4a8357b99ec.png">

**Comment by Bergrebell** [comment] 2022-11-08 16:25
this is the content of `avo.custom.js`

```
function initMap() {
    const city = {
        lat: 46.94261797313208,
        lng: 7.432553971123764,
    };

    console.log(city)

    const map = new google.maps.Map(document.getElementById("map"), {
        zoom: 10,
        center: city
    });

    console.log(map)
}

window.initMap = initMap;
initMap()
```

The logs only work because i call initMap() on the last line of the file. The callback in <script> does not call initMap at all.

**Comment by adrianthedev** [comment] 2022-11-08 22:54
So the issue here isn't with Avo. It's the order in which the browser loads and executes the JS content.

What's happening is that the script from Google gets executed before your script.
One way to fix it would be to add `defer="true"` to the maps script tag. This way, even if the browser loads the script, it will pause execution until the whole page is loaded (and your script too).

I managed to get that to load but I'm not using importmaps. Not sure how that might affect it.

![CleanShot 2022-11-09 at 00 51 11](https://user-images.githubusercontent.com/1334409/200693101-aae76795-37bf-4a4b-8f4a-c46c6fc1be57.jpg)

**Comment by Bergrebell** [comment] 2022-11-09 12:42
Thanks a lot for you fast reply! 

When doing so it loads the map when i directly visit it or do a reload in the browser. But when i navigate from another avo page without a reload it won't show up. Any ideas? 

Also in general - would you recommend me to load it in the _head.html.erb or in the _pre_head.html.erb?

**Comment by adrianthedev** [comment] 2022-11-09 14:36
Again, this is not related to Avo, but with how the JS is being loaded.

So you are creating a function `initMap` which you make global, so anyone can execute. Then you load up the gmap script which will execute that function.
The issue is that if you go on a different page than the one with the `#map` div, the function will get executed and the div will be inexistent (which is the error you'll see in the console).

![CleanShot 2022-11-09 at 16 29 40](https://user-images.githubusercontent.com/1334409/200856826-bcafc18e-155b-4e62-919d-3ba218a969fc.jpg)

There are two options:

1. What you need to do is make a more complex loading mechanism where `initMap` doesn't try to instantiate the map, but only changes a variable somewhere in your JS the "the google script has loaded and the `window.google` object is available". Then, the same script will wait for the user to navigate to the proper page and then instantiate the map `const map = new google.maps.Map(document.getElementById('map')...` and display it to the user. You could do that using a stimulus controller.

This is the preferred mechanism 👆

3. An alternative is to load the google script and a custom js script inside the tool `erb` partial instead of `_head`, but that's might give you troubles in the future.

This is what that article demos anyway _The only thing left to do now is set up our view so that the Google Maps API is called and uses our JavaScript code to build the map_. Put the HTML, the custom script, and the google script in the same view.

Once more, this is not an Avo issue, but a google maps & JS matter 🙃

I hope this helps you.

Closing for now.

**Closed by adrianthedev** 2022-11-09 14:36 UTC

**Comment by Bergrebell** [comment] 2022-11-09 16:26
thanks again for the detailed answer @adrianthedev i really appreciate it! 

is there any way to use a stimulus-controller inside of a `avo:tool`? i haven't found anything to it in the docs unfortunately.

initializing the map in a plain rails app works easily with stimulus. but i cannot get it to work in the avo-tool.

**Comment by adrianthedev** [comment] 2022-11-09 16:49
Hmmm. It should just work. The flow is like this.

1. Create a stimulus controller in a separate `_controller.js` file
2. register it in the app in `avo.custom.js`
3. In the tool's erb file you initialize the controller in the HTML with `data-controller="YOUR_CONTROLLER"`

Have a look at [this commit](https://github.com/avo-hq/main.avodemo.com/commit/34dc59b9b533235c4171dc9dcf0108388e9bdc93) where I do all of that in the demo app.

**Comment by adrianthedev** [comment] 2022-11-09 17:21
Here's a step-by-step guide.

https://docs.avohq.io/2.0/stimulus-integration.html#use-stimulus-js-in-a-tool

**Comment by adrianthedev** [comment] 2022-11-11 13:30
This is interesting. Are you loading `avo.custom.js` using `defer="true"`? If not, then yes, there might be a race condition there (your script loads before Avo's).

**Comment by Bergrebell** [comment] 2022-11-11 13:54
i'm not using `defer="true"`. looks like a race condition ...

**Comment by adrianthedev** [comment] 2022-11-11 13:55
Yes. so, I think you should, just to be safe. This way, it will always load the scripts in the right order every time.

Otherwise, you should be good with using your own stimulus application.

**Comment by Bergrebell** [comment] 2022-11-11 13:57
perfekt! thanks. :)

the issue from `1.` in my previous post could be useful for the documentation i guess.
