### ISSUE TITLE
Problem with N+1 when access parent field in child resource

### ISSUE THREAD

**Issue by dailson-igo** [avo-hq/avo#1795] opened 2023-06-19 15:22 UTC
### Context
I need to use in the self.title of a child table (Post) resource a field that is in the parent table (Category)

### Model to Parent Table
```
$ r g model category name_field_example:string description:text
```

### Model to Child Table
```
$ rails g model post title:string body:text category:references
```

### app/model/post.rb
```
  belongs_to :category

  # When I create a method (def name_field_example do) in the child table, the N+1 problem happens!  
  def name_field_example
    category.name_field_example
  end
```

```
class PostResource < Avo::BaseResource
  self.title = :name_field_example      # stay in category
  self.includes = [:category]
  # self.search_query = -> do
  #   scope.ransack(id_eq: params[:q], m: "or").result(distinct: false)
  # end

  field :id, as: :id
  # Fields generated from the model
  field :title, as: :text
  field :body, as: :textarea
  # add fields here
end
```

### Third Level Model
```
$ rails g model third_level title:string body:text post:references
```

### System configuration
**Avo version**: 2.35.0

**Rails version**: 7.0.5

**Ruby version**: 3.2.2

**License type**

 - [ X ] Community
 - [ ] Pro

**Are you using Avo monkey patches, overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [ X ] No

**Comment by adrianthedev** [comment] 2023-06-19 15:33
What is the page (path) you are getting the n+1?

**Comment by dailson-igo** [comment] 2023-06-20 13:26
> What is the page (path) you are getting the n+1?

Sorry for the inaccuracy.
Occurs only from the third level of the relationship. I isolated the situation and put it on GitHub

https://github.com/dailson-igo/avo_nplusone

GET /avo/resources/third_levels
USE eager loading detected
  Post => [:category]
  Add to your query: .includes([:category])
Call stack
  /home/igo/vscode/ruby/avo_nplusone/app/models/post.rb:5:in `name_field_example'

**Comment by adrianthedev** [comment] 2023-06-20 15:46
ok. I managed to get the same result, but that's not an Avo issue and the suggestion from `bullet`is not correct.
I mean, if you add `self.includes = [:post, :category]` to the `ThirdLevelResource` is the same as adding `.includes([:category])` to the query.
But that won't work because the `Post` doesn't have an association with `category`.

The fix here is to add `.include(post: [:category])` which translates into `self.includes = [post: [:category]]` in Avo (most things you can do outside of Avo you can do inside too).

Thanks for the reproduction repo. That helped a lot to understand the situation and provide a fix.

So the fix is `self.includes = [post: [:category]]` on `ThirdLevelResource`.

Closing for now. Please feel free to reopen.

**Closed by adrianthedev** 2023-06-20 15:46 UTC

**Comment by adrianthedev** [comment] 2023-06-20 17:12
I think more levels means you turn the item into a hash (judging after this post).

```ruby
self.includes = [post: {category: {level_three: [:level_four]}}]
```

An entry to the [docs](https://github.com/avo-hq/avodocs) would be very useful. Would you mind opening up a PR?
