### ISSUE TITLE
has_many through not working in Avo

### ISSUE THREAD

**Issue by jmarsh24** [avo-hq/avo#1294] opened 2022-10-07 10:57 UTC
### Context
https://gist.github.com/jmarsh24/781b3575be52e841db4bcd1c57cc1c9e

Currently I have a has_many through association between theme, category resource, and theme_categories. 

The association works in rails both ways, but only theme->categories but not category->themes.

Do you have any advice on what to do here to troubleshoot?

### System configuration
**Avo version**: 2.14.2

**Rails version**: 7.0.4

**Ruby version**: 3.1.2

**License type** (Community or Pro): Pro

### Screenshots

![image](https://user-images.githubusercontent.com/48605824/194537947-04444841-ae11-41bd-b89f-0f8b93d2eb08.png)

![image](https://user-images.githubusercontent.com/48605824/194537965-6a85ad66-7a76-4250-a08e-bb1a948d5183.png)

**Comment by adrianthedev** [comment] 2022-10-07 10:59
This is weird. I checked Avo source code, and it doesn't have a `raw?` method.
Can you check your source code and see if that could be the issue?

**Comment by adrianthedev** [comment] 2022-10-07 11:01
Also, on what page are you getting that error?

**Comment by adrianthedev** [comment] 2022-10-07 11:01
From the information provided, I can't see that `visible` block where you call the `raw?` method.

**Comment by jmarsh24** [comment] 2022-10-07 11:01
```ruby
  self.visible = ->(resource:, view:) do
    resource.model&.then { |m| (m.raw? || m.problem?) && m.source_archive.attached? }
  end
  ```
  
  I had this on an AnalyzeTheme < Avo::BaseAction which is causing the issue

**Comment by adrianthedev** [comment] 2022-10-07 11:03
Ok. So the issue is in the action. Does it happen when you want to see the action (select a record from the index page and then open the action) or when you run it?

**Comment by adrianthedev** [comment] 2022-10-07 11:03
Actually, can you make a screen recording on how that's happening?

**Comment by jmarsh24** [comment] 2022-10-07 11:04
The error occurs when I want to display the has_many records on the category. I’m not running any actions.

**Comment by adrianthedev** [comment] 2022-10-07 11:10
ok. let me try and reproduce it

**Comment by jmarsh24** [comment] 2022-10-07 11:15
I think it's an issue on my end not with Avo. I was just puzzled by the error. When I remove the visible constraint it works ok.

**Comment by adrianthedev** [comment] 2022-10-07 11:17
Yes. My guess is that's where the issue is. Are you using the action on multiple resources? If so, then some model `Category` does not have the `raw?` method.

**Comment by adrianthedev** [comment] 2022-10-07 21:01
Not sure if you figured the issue with this, but closing for now. Feel free to reopen.

**Closed by adrianthedev** 2022-10-07 21:01 UTC
