### ISSUE TITLE
attach_{association}? not working

### ISSUE THREAD

**Issue by jmarsh24** [avo-hq/avo#1374] opened 2022-10-28 11:53 UTC
### Describe the bug
If you create a parent resource with a has_many association then add an attach_{association}? policy on the parent pundit policy then it doesn't remove the attach {resource}? button.

### Steps to Reproduce
https://gist.github.com/jmarsh24/97552e35807d03df16ba17270d09772c

### Expected behavior & Actual behavior
Adding false to attach_{association}? in pundit should remove the attach? button.

### Models and resource files
[](https://gist.github.com/jmarsh24/97552e35807d03df16ba17270d09772c)

### System configuration
**Avo version**:2.17.0

**Rails version**: 7.0.4

**Ruby version**:3.1.2

**License type**:

 - [ ] Community
 - [x] Pro

**Are you using Avo monkey patches or overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [x] No

#### Impact

 - [ ] High impact
 - [ ] Medium impact
 - [x] Low impact

#### Urgency

 - [ ] High urgency
 - [ ] Medium urgency
 - [x] low urgency

**Comment by adrianthedev** [comment] 2022-10-28 14:48
Hey @jmarsh24 can you try the plural name please `def attach_scenes?` instead of `def attach_scene?`?

The `{association}` part refers to the exact key you called for the field name.

Example: for `field :pickers, as: :has_many` the policy method would be `attach_pickers?`.

The reasoning is that you might as well have a `has_one` `:picker`, and the method for that would be `attach_picker?`

**Comment by jmarsh24** [comment] 2022-10-28 15:02
@adrianthedev I have tried both plural and singular and neither work. 🤔

**Comment by adrianthedev** [comment] 2022-10-28 15:13
@jmarsh24 can you try Avo 2.18? We pushed some changes that should fix that.

**Comment by jmarsh24** [comment] 2022-10-28 15:20
It's still an issue on 2.18

**Comment by adrianthedev** [comment] 2022-10-28 15:22
Hmmm. That's weird. 

I just tested it on local and the attach button disappears like it should.

Please create an app to reproduce that issue so I can have a look.

**Comment by adrianthedev** [comment] 2022-11-02 19:40
Closing for now. Feel free to reopen if the issue is still there.

**Closed by adrianthedev** 2022-11-02 19:40 UTC
